### PR TITLE
LSP formatting

### LINKED ISSUE #192: [Feature] Fallback to LSP formatting if no formatter is configured
Love the project! Just one suggestion:

It would be nice to have an option, in some form, to fall back to LSP formatting if a formatter is not configured. Some languages do not have external formatters (or what does exist is subpar), and in other cases it is simply too much effort to install one for a small snippet.

Given the design of the project, a default `all` formatter would likely be the solution here.

### PR DESCRIPTION
**Pull request by nullishamy**
Closes #192

### CODE REVIEW

**Comment by Diablo-D3** [comment]
@mhartington Can you consider taking a look at this one? The code seems to look sane, and it also closes the issue of requiring two (possibly conflicting) augroups to format on save (thus simplifying everyone's configs) while also allowing LSP-enabled buffers to call formatter.nvim if the LSP in use does not impl LSP formatting.

**Comment by nullishamy** [comment]
@mhartington Any updates on this one?

**Comment by mhartington** [comment]
So in testing this out, I kept getting this error for typescript


```
Finished running prettier
Failed to run formatter lsp-format. ...ker/start/formatter.nvim/lua/formatter/filetypes/any.lua:21: LSP tsserver returned an error RPC[Error] code_name = InvalidP
arams, message = "Request textDocument/formatting defines parameters by name but received parameters by position"
```

And for python, 


```
Failed to run formatter lsp-format. ...ker/start/formatter.nvim/lua/formatter/filetypes/any.lua:21: LSP pylsp returned an error RPC[Error] code_name = InvalidParams, message = "TypeError: 'NoneType' object is not subscriptable" data = {  traceback = { "  File \"/usr/local/lib/python3.9/site-packages/pylsp_jsonrpc/endpoint.py\", line 116, in consume\n    self._handle_request(message['id'], message['method'], message.get('params'))\n", '  File "/usr/local/lib/python3.9/site-packages/pylsp_jsonrpc/endpoint.py", line 185, in _handle_request\n    handler_result = handler(params)\n', '  File "/usr/local/lib/python3.9/site-packages/pylsp_jsonrpc/dispatchers.py", line 25, in handler\n    return method(**(params or {}))\n', "  File \"/usr/local/lib/python3.9/site-packages/pylsp/python_lsp.py\", line 345, in m_text_document__formatting\n    return self.format_document(textDocument['uri'])\n" }}
```


Any ideas?

**Comment by nullishamy** [comment]
Does it work for other LSPs? If so, we'd need to special case it somehow. Nvim might offer a higher level API for dealing with the clients, but I'm not sure.

**Comment by max397574** [comment]
perhaps just use vim.lsp.buf.format() instead of writing your own function?

**Comment by nullishamy** [comment]
> perhaps just use vim.lsp.buf.format() instead of writing your own function?

Afaik that launches the selection window, which was something I was trying to avoid.

**Comment by max397574** [comment]
if you just want to use the first one this should be possible with `filter`
I think you could do something like `filter=function()if not first then first=true; return true end`
haven't tried it though

**Comment by max397574** [comment]
https://github.com/neovim/nvim-lspconfig/wiki/Multiple-language-servers-FAQ#i-see-multiple-formatting-options-and-i-want-a-single-server-to-format-how-do-i-do-this

**Comment by Diablo-D3** [comment]
Maybe the real issue is `vim.lsp.buf.format()` can't call formatter.nvim when an LSP isn't loaded?

**Comment by nullishamy** [comment]
> https://github.com/neovim/nvim-lspconfig/wiki/Multiple-language-servers-FAQ#i-see-multiple-formatting-options-and-i-want-a-single-server-to-format-how-do-i-do-this @nullishamy

Yeah, this is basically what I implemented, no?

**Comment by Hrle97** [comment]
> Yeah, this is basically what I implemented, no?

Seems like it. Will take a look once I'm done with work today.

**Comment by mhartington** [comment]
Works been crazy for me the past few weeks (about a month). So some things I've noticed while testing...

- lsp format returns nil if no changes: this should return an empty table 

```
Failed to run formatter lsp-format. ...tington/bin/nvim/share/nvim/runtime/lua/vim/lsp/util.lua:393: text_edits: expected table, got nil
```
- The complete func needs to be updated to account for a formatter who's exe is a lua function and provides a name. A very quick fix could be: 

```diff
@@ -11,7 +11,7 @@ function M.complete(args)
   for _, formatter_function in ipairs(formatters) do
     local formatter = formatter_function()
     if formatter ~= nil then
-      local exe = formatter.exe
+      local exe = formatter.name or formatter.exe
       if string.match(exe, input) then
         table.insert(completion, exe)
       end
```

**Comment by mhartington** [comment]
Another thing to keep in mine, if mixing both lsp and another formatter, the flow of handing changes between running multiple tools will break. 

```
Buffer changed while formatting, not applying formatting
```

Since we currently only read the buffer once and then pass the formatted lines between multiple tools, we would need to either rethink how this is done, or figure out how to get the edits from lsp and apply them to a temp file or something.



Honestly, I'm feeling less confident in this PR in genreal and the idea of mixing external tools with built-in neovim functionality.

**Comment by mhartington** [comment]
Converting this to a draft for now until the bugs are resolved first.

**Comment by nullishamy** [comment]
Closing as I no longer have time to work on this one. If someone else wants to pick it up, they can!

**Pull request closed without merging**
