### PR TITLE
Update readme contributing

### PR DESCRIPTION
**Pull request by Hrle97**
update `README.md` and `CONTRIBUTING.md`

### CODE REVIEW

**Comment by Hrle97** [comment]
related to #137

**Comment by Hrle97** [comment]
converted to a draft because it needs more discussion

**Comment by mhartington** [comment]
Reviewing what's been done so far, seems pretty reasonable.

**Comment by David-Else** [comment]
This plugin looks great, I am really interested in the presets, but I had to search to find this pull request to learn how to use them. As the presets have been merged, please merge this or nobody knows how to use them.

**Comment by Hrle97** [comment]
Yeah I'm just waiting for @mhartington approval. Btw I got an invite for this project but I kinda forgot about it and now its expired, eheh.

**Review by mhartington — APPROVED** [review]

**Comment by mhartington** [comment]
As and you shall receive!

**Comment by mhartington** [comment]
BTW @Hrle97 I resent the the invite!

**Pull request merged**
