### PR TITLE
Default configurations ported from neoformat

### PR DESCRIPTION
**Pull request by Hrle97**
Ported formatter configurations for the following filetypes from `neoformat`:
 - javascript
 - javascriptreact
 - typescript
 - typescriptreact
 - css
 - html
 - go
 - rust
 - python
 - lua

The structure of these configurations is:
```lua
-- lua/formatter/filetypes/typescript.lua

local M = {}

M. prettier  =  function()
  return {
    exe = "prettier",
    args = {...},
    stdin = true
  }
end

-- other formatters...

return M
```
, as decided in #97.

Usage of these configurations is explained in the newly written `CONFIG.md`.

The original structure of configurations was changed to this to fit newly added default configurations:
 - `exe`: the program you wish to run.
 - `args`: a table of args to pass. (optional)
 - `stdin`: If it should use stdin or not. (optional)
 - `cwd` : The path to run the program from. (optional)
 - `try_node_modules`: Tries to run a formatter from locally install npm packages (optional) (to be implemented)
 - `no_append` : Don't append the path of the file to the formatter command (optional)
 - `ignore_exitcode` : Set to true if the program expects non-zero success exit code (optional)
 - `tempfile_dir`: directory for temp file when not using stdin (optional)
 - `tempfile_prefix`: prefix for temp file when not using stdin (optional)

Other miscellaneous changes:
 - added [`.luacheckrc`](https://github.com/mpeterv/luacheck) file
 - added [`stylua.toml`](https://github.com/johnnymorganz/stylua) file

The PR will be a draft for now until I test and validate the added formatter configurations a bit more after which I will mark it as ready for review and add a `CONTRIBUTING.md` file, Vim help file, and update the `README.md` file.

### CODE REVIEW

**Comment by mjlbach** [comment]
One issue with this approach, is there is a ton of duplication of formatters (clang-format is mostly duplicated intact 6 times). I think a more sustainable approach would be to individually list all formatters under a common directory, with each formatter getting its own filetype. I think users can be expected to look up and choose their formatter based on filetype.


I personally find a lot of these changes to be unnecessary/should be factored out into their own PRs, the readme is IMO way too long now (I wrote some opinions on this fwiw in https://neovim.discourse.group/t/documentation-and-onboarding-new-users/1331) especially considering the presence of the vimdoc, attributions to neomake should probably be at the end, not at the beginning.

**Comment by Hrle97** [comment]
> One issue with this approach, is there is a ton of duplication of formatters (clang-format is mostly duplicated intact 6 times). I think a more sustainable approach would be to individually list all formatters under a common directory, with each formatter getting its own filetype. I think users can be expected to look up and choose their formatter based on filetype.

I also noticed this as I was writing this. What do you say about creating a directory called `formatters` or `formatter_defaults` that has files which export factories for formatter configurations?

A good example for this is `prettier`. Let's say we have a factory for `prettier` inside `lua/formatter/formatters/prettier.lua` like this:

```lua
local util = require("formatter.util")

return function(parser)
  -- instruct prettier to use a specific parser
  if parser then
    return {
      exe = "prettier",
      args = {
        "--stdin-filepath",
        util.escape_path(util.get_current_buffer_file_path()),
        "--parser",
        parser,
      },
      stdin = true,
      try_node_modules = true,
    }
  end

  -- use the default prettier parser
  return {
    exe = "prettier",
    args = {
      "--stdin-filepath",
      util.escape_path(util.get_current_buffer_file_path()),
    },
    stdin = true,
  }
end
```

Now we can use this to create a `prettier` config for `javascript` in `lua/formatter/filetypes/javascript.lua` like this:

```lua
local M = {}

-- other formatters...

function M.prettier()
  -- using the default javascript parser
  return require("formatter.formatters.prettier")()
end

-- other formatters...

return M
```

and a `prettier` config for `typescript` in `lua/formatter/filetypes/typescript.lua` like this:

```lua
local M = {}

-- other formatters...

function M.prettier()
  -- using the typescript parser
  return require("formatter.formatters.prettier")("typescript")
end

-- other formatters...

return M
```

> I personally find a lot of these changes to be unnecessary/should be factored out into their own PRs, the readme is IMO way too long now (I wrote some opinions on this fwiw in https://neovim.discourse.group/t/documentation-and-onboarding-new-users/1331) especially considering the presence of the vimdoc, attributions to neomake should probably be at the end, not at the beginning.

I know its a lot of changes and I could make separate PRs for these, but that would just require more work. I could improve some of the changes instead or you could be more specific on what changes are good and what changes are bad.

I could make the `README.md` shorter and more welcome to new users by adding `CONTRIBUTING.md` and referring more to the vimdoc for advanced users, following the guidelines you specified in that link and moving the attributions to `neoformat` at the very end of the `README.md`.

Some of the changes to the files were a result of me using `stylua`, so I could restore those changes, but I would find that a bit ironic considering that this is a fomatter plugin.

Some of the changes I made were a result of me using `luacheck` and adding the `.luacheckrc` file to keep the linter happy. I like using linters, but I understand that some people don't, so I can restore some of those, but its mostly making the code easier to read and less bug prone.

I could also rename this PR into something like `Default configurations ported from neoformat and refactoring` if you'd like so that its more clear that I changed the plugin more than I initially said I would (not the behaviour, but the organization of code).

**Comment by mhartington** [comment]
Hey, thanks for the initial work here. To address @mjlbach's comments, I agree with the formatting file structure

Let's go with some middle ground where we have a file for each formatter.

```lua
--  ./lua/formatter/defaults/prettier.lua

local M = {}

M.prettier = function()
  return {
    exe = "prettier",
    args = {"--stdin-filepath", vim.fn.shellescape(vim.api.nvim_buf_get_name(0)) },
    stdin = true
  }
end

return M
```

Then users can consume this like so...

```lua
formatter.setup(
  {
    filetype = {
      typescript = {
        require("formatter.defaults.prettier")()
      },
      javascript = {
        require("formatter.defaults.prettier")()
      }
    },
    log_level = 2
  }
)

```

What do you think of something like this? @Hrle97 and @mjlbach 


On another note, I would hold off on the extra changes around the config/readme until the actual formatter work is done. I would agree with @mjlbach here. Plus it makes diffing this PR pretty difficult.

**Comment by mjlbach** [comment]
> I would hold off on the extra changes around the config/readme until the actual formatter work is done. I would agree with @mjlbach here. Plus it makes diffing this PR pretty difficult.

+ 1

```lua
--  ./lua/formatter/defaults/prettier.lua

local M = {}

M.prettier = function()
  return {
    exe = "prettier",
    args = {"--stdin-filepath", vim.fn.shellescape(vim.api.nvim_buf_get_name(0)) },
    stdin = true
  }
end

return M
```

I would say that you could just directly return the function (or a table) itself? That avoids the need for a require('prettier').prettier

**Comment by mhartington** [comment]
>I would say that you could just directly return the function (or a table) itself? That avoids the need for a require('prettier').prettier


Since the formatter needs to invoke a function internally, would it make more sense to have...


```lua
filetype = {
  typescript = {
    function() require('formatter.defaults.prettier') end,
  }
}
```

or 

```lua
filetype = {
  typescript = {
     require('formatter.defaults.prettier'),
  }
}

```

We can return what ever format make sense, table or function. Just what make sense from a users perspective.

**Comment by Hrle97** [comment]
> On another note, I would hold off on the extra changes around the config/readme until the actual formatter work is done. I would agree with @mjlbach here. Plus it makes diffing this PR pretty difficult.

I've been rethinking this more and I agree. Is it okay if I create separate PRs (branch names in braces) for Vim help (vim-help), stylua (stylua - should I format the whole repo once I add it?), luacheck (luacheck), and README/CONTRIBUTING (readme)?

The rest of the changes should remain a part of this PR, so that this PR actually works (formatter config changes) or I can add a separate PR with those and we could merge that before this one.

I was planning on doing this over the weekend again.

This looks good (returning just a single function from a default formatter config module)
> or
```lua
filetype = {
  typescript = {
     require('formatter.defaults.prettier')(),
  }
}
```

, but I think that this would be even better (we make both ways possible by just adding an `init.lua` file in defaults directory):

```lua
local defaults = require('formatter.defaults')
filetype = {
  typescript = {
     defaults.prettier(),
  }
}
```

Just note that my initial proposal for `prettier` accepts a single argument for the parser, so users could do something like this:
```lua
local defaults = require('formatter.defaults')
filetype = {
  typescript = {
     defaults.prettier('typescript'),
  }
}
```

Keep in mind that this is just default configurations per formatter and not per filetype to escape boilerplate in default configurations per filetype, but these can also be used by users. Here is my initial proposal of how these would be used for default configurations per filetype:

```lua
-- lua/formatter/filetypes/javascript.lua

local M = {}

-- other formatters...

function M.prettier()
  -- using the default javascript parser
  return require("formatter.defaults.prettier")()
end

-- other formatters...

return M
```

```lua
-- lua/formatter/filetypes/typescript.lua

local M = {}

-- other formatters...

function M.prettier()
  -- using the typescript parser
  return require("formatter.defaults.prettier")("typescript")
end

-- other formatters...

return M
```

**Comment by lukas-reineke** [comment]
> stylua - should I format the whole repo once I add it?

please do

**Comment by Hrle97** [comment]
@mhartington sry for the delay - checkout the new PR please
i opened up other PR's for other stuff related to this

**Comment by mhartington** [comment]
@Hrle97 thank you! I'll get to reviewing the PRs. Is it safe to close this one?

**Pull request closed without merging**
