### PR TITLE
Vim help

### PR DESCRIPTION
**Pull request by Hrle97**
add a basic Vim help file

### CODE REVIEW

**Comment by Hrle97** [comment]
related to #137

**Comment by Hrle97** [comment]
converted to a draft for now because it needs more discussion

**Comment by mhartington** [comment]
Reviewing what's been done so far, seems pretty reasonable.

**Comment by Hrle97** [comment]
@mhartington do u wanna merge this one now as well? its pretty much the same as #135 but in Vim help format

**Pull request merged**
