### PR TITLE
shell escape fix

### PR DESCRIPTION
**Pull request by Hrle97**

### CODE REVIEW

**Comment by Hrle97** [comment]
TODO: check on windows

**Comment by lalitmee** [comment]
When can this PR be merged?

**Comment by Hrle97** [comment]
sry ive been away for a while

anyone by chance checked this on windows?

**Comment by lalitmee** [comment]
@Hrle97, I think we can merge this. If someone on windows finds any bug in this bug they can come back there and raise a bug.

I could check this on windows, but I don't have one installed.

**Pull request merged**
