### PR TITLE
[FORMAT] Execute formatter from the CWD of the file being formatted.

### PR DESCRIPTION
**Pull request by jameswalmsley**
Most formatters will move up the directory tree to find their nearest
parent for configuration and apply that style.

This could be configured as an option, or be defaulted to on?

### CODE REVIEW

**Comment by lukas-reineke** [comment]
This should definitely not be the default.
Formatters should run from the current directory in basically all cases I can think of.

Why would you want to run it from the file path?

**Comment by jameswalmsley** [comment]
E.g. clang-format searches for the nearest .clang-format from where the current file exists.

This is really important for projects that contain multiple sources with different styling options.

I'd be happy to make this a configurable option... can you find a formatter that doesn't like this?

**Comment by lukas-reineke** [comment]
I see
For monolithic projects with different styles, this would make sense.

If it's an option, it should be no problem to add.
Instead of just a boolean for file path or root path, it would probably be nice to directly expose `cwd` as an option. Then users can pass whatever path they want.

**Comment by jameswalmsley** [comment]
Yes that makes sense.. I think I would allow the user to specify a function that obtains the cwd.. 

So that it can run in the context of the current buffer..  and not something that's set at configure time.

I think that should cover all possible cases.. 

I'll update the PR with an example..

**Comment by jameswalmsley** [comment]
Sorry I messed up my git push, and this got closed.. see #58

**Pull request closed without merging**
